### PR TITLE
Pobrien/add timeout to tests

### PR DESCRIPTION
**Pull request by vanchi-zendesk**
Slow sentinel and redis start/stop times are causing tests to fail.  Add timeouts to fix this problem.

### CODE REVIEW

**Comment by vanchi-zendesk** [comment]
Can you setup travis for this?

**Comment by bolddane** [comment]
OK, so I needed to configure this repo via my travis-ci.org profile, after which I need to commit a change to trigger the build.

**Comment by vanchi-zendesk** [comment]
We should change the license to Apache V2 :-)

**Comment by lucasefe** [comment]
:+1:

**Comment by vanchi-zendesk** [comment]
:+1:

**Pull request merged**
